module.exports = {
  siteTitle: "tfblog - made by Gatsbyjs", // <title>
  shortSiteTitle: "tfblog - made by Gatsbyjs", // <title> ending for posts and pages
  siteDescription: "tfBlog is made by Gatsbyjs.",
  siteUrl: "https://takanorifukuyama.com",
  pathPrefix: "",
  siteImage: "preview.jpg",
  siteLanguage: "ja",

  /* author */
  authorName: "Takanori Fukuyama",
  authorTwitterAccount: "thisistakanori",

  /* info */
  headerTitle: "Takanori Fukuyama",
  headerSubTitle: "this site is generated by gatsbyjs",

  /* manifest.json */
  manifestName: "tfblog - made by Gatsbyjs",
  manifestShortName: "tfBlog", // max 12 characters
  manifestStartUrl: "/index.html",
  manifestBackgroundColor: "white",
  manifestThemeColor: "#666",
  manifestDisplay: "standalone",

  // gravatar
  // Use your Gravatar image. If empty then will use src/images/jpg/avatar.jpg
  // Replace your email adress with md5-code.
  // Example https://www.gravatar.com/avatar/g.strainovic@gmail.com ->
  // gravatarImgMd5: "https://www.gravatar.com/avatar/1db853e4df386e8f699e4b35505dd8c6",
  gravatarImgMd5: "",

  // social
  authorSocialLinks: [
    { name: "github", url: "https://github.com/takanorifukuyama" },
    { name: "twitter", url: "https://twitter.com/thisistakanori" },
    { name: "facebook", url: "http://facebook.com/thisistakanori" }
  ]
};
